import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // ✅ Google Fonts에서 Geist 폰트 가져오기
import "./globals.css"; // ✅ 전역 CSS 가져오기

// 📌 Google Fonts: Geist Sans & Geist Mono 설정
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 🌍 페이지 메타데이터 설정
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 🏷️ Root Layout 컴포넌트
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
